In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\simon\miniconda3\lib\site-packages (1.2.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\simon\miniconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\simon\miniconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\simon\miniconda3\lib\site-packages (from pandas) (1.20.0)
Requirement already satisfied: six>=1.5 in c:\users\simon\miniconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [10]:
import pandas as pd

In [11]:
fat_supply_quantity_data = pd.read_csv('fat_supply_quantity_data.csv')

In [12]:
fat_supply_quantity_data

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,21.6397,6.2224,0.0,8.0353,0.6859,0.0327,0.4246,6.1244,...,17.0831,0.3593,4.5,29.8,0.138283,0.005970,0.116713,0.015601,38928000.0,%
1,Albania,0.0000,32.0002,3.4172,0.0,2.6734,1.6448,0.1445,0.6418,8.7428,...,9.2443,0.6503,22.3,6.2,2.347956,0.044574,1.396230,0.907153,2838000.0,%
2,Algeria,0.0000,14.4175,0.8972,0.0,4.2035,1.2171,0.2008,0.5772,3.8961,...,27.3606,0.5145,26.6,3.9,0.233066,0.006373,0.158234,0.068458,44357000.0,%
3,Angola,0.0000,15.3041,1.3130,0.0,6.5545,0.1539,1.4155,0.3488,11.0268,...,22.4638,0.1231,6.8,25,0.057435,0.001316,0.049566,0.006552,32522000.0,%
4,Antigua and Barbuda,0.0000,27.7033,4.6686,0.0,3.2153,0.3872,1.5263,1.2177,14.3202,...,14.4436,0.2469,19.1,NaN,0.187755,0.006122,0.159184,0.022449,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.0000,16.3261,2.2673,0.0,2.5449,0.6555,0.5707,0.9640,7.0949,...,29.5211,0.1851,25.2,21.2,0.414928,0.003823,0.392110,0.018995,28645000.0,%
166,Vietnam,0.0000,33.2484,3.8238,0.0,3.7155,0.7839,1.1217,0.4079,26.4292,...,5.6211,0.6373,2.1,9.3,0.001597,0.000036,0.001434,0.000126,96209000.0,%
167,Yemen,0.0000,12.5401,2.0131,0.0,11.5271,0.5514,0.3847,0.2564,8.0010,...,23.6312,0.1667,14.1,38.9,0.007078,0.002052,0.004758,0.000268,29826000.0,%
168,Zambia,0.0783,9.6005,1.6113,0.0,14.3225,0.6266,1.0070,0.1343,4.9010,...,15.2848,0.1567,6.5,46.7,0.186456,0.002867,0.131119,0.052470,18384000.0,%
169,Zimbabwe,0.0000,10.3796,2.9543,0.0,9.7922,0.3682,0.2455,0.0614,4.5674,...,26.9396,0.0789,12.3,51.3,0.175664,0.004481,0.103707,0.067476,14863000.0,%

In [14]:
excel_file_path = 'fat_supply_quantity_data.csv'

In [15]:
df = pd.read_csv(excel_file_path)

In [16]:
print(df.columns)

Index(['Country', 'Alcoholic Beverages', 'Animal Products', 'Animal fats',
       'Aquatic Products, Other', 'Cereals - Excluding Beer', 'Eggs',
       'Fish, Seafood', 'Fruits - Excluding Wine', 'Meat', 'Miscellaneous',
       'Milk - Excluding Butter', 'Offals', 'Oilcrops', 'Pulses', 'Spices',
       'Starchy Roots', 'Stimulants', 'Sugar Crops', 'Sugar & Sweeteners',
       'Treenuts', 'Vegetal Products', 'Vegetable Oils', 'Vegetables',
       'Obesity', 'Undernourished', 'Confirmed', 'Deaths', 'Recovered',
       'Active', 'Population', 'Unit (all except Population)'],
      dtype='object')

In [17]:
df_info = df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       170 non-null    object
 1   Alcoholic Beverages           170 non-null    float64
 2   Animal Products               170 non-null    float64
 3   Animal fats                   170 non-null    float64
 4   Aquatic Products, Other       170 non-null    float64
 5   Cereals - Excluding Beer      170 non-null    float64
 6   Eggs                          170 non-null    float64
 7   Fish, Seafood                 170 non-null    float64
 8   Fruits - Excluding Wine       170 non-null    float64
 9   Meat                          170 non-null    float64
 10  Miscellaneous                 170 non-null    float64
 11  Milk - Excluding Butter       170 non-null    float64
 12  Offals                        170 non-null    float64
 13  Oilcrops                      170 non-null    float64
 14  Pulses                        170 non-null    float64
 15  Spices                        170 non-null    float64
 16  Starchy Roots                 170 non-null    float64
 17  Stimulants                    170 non-null    float64
 18  Sugar Crops                   170 non-null    float64
 19  Sugar & Sweeteners            170 non-null    float64
 20  Treenuts                      170 non-null    float64
 21  Vegetal Products              170 non-null    float64
 22  Vegetable Oils                170 non-null    float64
 23  Vegetables                    170 non-null    float64
 24  Obesity                       167 non-null    float64
 25  Undernourished                163 non-null    object
 26  Confirmed                     164 non-null    float64
 27  Deaths                        164 non-null    float64
 28  Recovered                     164 non-null    float64
 29  Active                        162 non-null    float64
 30  Population                    170 non-null    float64
 31  Unit (all except Population)  170 non-null    object
dtypes: float64(29), object(3)
memory usage: 42.6+ KB

In [19]:
print(df.describe())

       Alcoholic Beverages  Animal Products  Animal fats  \
count           170.000000       170.000000   170.000000
mean              0.001035        20.695714     4.138451
std               0.009569         8.002713     3.287462
min               0.000000         5.018200     0.026200
25%               0.000000        14.885800     1.674225
50%               0.000000        20.943050     3.312350
75%               0.000000        26.866950     6.227575
max               0.097600        36.901800    14.937300

       Aquatic Products, Other  Cereals - Excluding Beer        Eggs  \
count               170.000000                170.000000  170.000000
mean                  0.000450                  4.376548    0.953890
std                   0.004039                  3.183815    0.643957
min                   0.000000                  0.990800    0.058000
25%                   0.000000                  1.970150    0.411350
50%                   0.000000                  3.306750    0.898300
75%                   0.000000                  5.587600    1.276900
max                   0.051100                 18.376300    3.275600

       Fish, Seafood  Fruits - Excluding Wine        Meat  Miscellaneous  ...  \
count     170.000000               170.000000  170.000000     170.000000  ...
mean        0.850437                 0.542117    9.494279       0.056589  ...
std         0.924103                 0.838286    4.666762       0.072633  ...
min         0.017400                 0.037300    0.906100       0.000000  ...
25%         0.330975                 0.239500    6.263575       0.010125  ...
50%         0.572700                 0.361400    9.259000       0.031650  ...
75%         1.111625                 0.577800   11.750450       0.076325  ...
max         8.406800                 9.672700   26.429200       0.456100  ...

         Treenuts  Vegetal Products  Vegetable Oils  Vegetables     Obesity  \
count  170.000000        170.000000      170.000000  170.000000  167.000000
mean     0.698955         29.304396       18.571657    0.309512   18.707784
std      0.814828          8.002369        6.766615    0.211766    9.633557
min      0.000000         13.098200        4.954900    0.026300    2.100000
25%      0.137350         23.133050       13.812825    0.173675    8.500000
50%      0.452400         29.060600       18.192550    0.247450   21.200000
75%      0.914025         35.117250       23.597300    0.362925   25.700000
max      4.975600         44.981800       36.418600    1.153800   45.600000

        Confirmed      Deaths   Recovered      Active    Population
count  164.000000  164.000000  164.000000  162.000000  1.700000e+02
mean     1.769148    0.033836    1.225827    0.513730  4.452364e+07
std      2.073808    0.042475    1.618107    1.170016  1.564182e+08
min      0.000312    0.000000    0.000000    0.000000  5.400000e+04
25%      0.120609    0.001687    0.077640    0.010835  2.816250e+06
50%      0.840729    0.010230    0.416784    0.084736  1.018150e+07
75%      2.926651    0.051884    2.124692    0.368980  3.271625e+07
max      8.799035    0.176743    7.223734    7.014216  1.402385e+09

[8 rows x 29 columns]